artifact_uri: /mlflow_server/0/e2eb063c613e4f8ab5cadc75e4a29125/artifacts
end_time: 1673437500873
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: e2eb063c613e4f8ab5cadc75e4a29125
run_uuid: e2eb063c613e4f8ab5cadc75e4a29125
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437500084
status: 3
tags: []
user_id: abdessamadbaahmed
