artifact_uri: /mlflow_server/0/f1f74629b9fa43959dd36f1e49b784d4/artifacts
end_time: 1673437493226
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f1f74629b9fa43959dd36f1e49b784d4
run_uuid: f1f74629b9fa43959dd36f1e49b784d4
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437492485
status: 3
tags: []
user_id: abdessamadbaahmed
