artifact_uri: /mlflow_server/0/81c8b8a11fef42f1ba22349de3663915/artifacts
end_time: 1673437492414
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 81c8b8a11fef42f1ba22349de3663915
run_uuid: 81c8b8a11fef42f1ba22349de3663915
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437491613
status: 3
tags: []
user_id: abdessamadbaahmed
