artifact_uri: /mlflow_server/0/1097f830ec604e0eb2be8a5b099da522/artifacts
end_time: 1673439202312
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1097f830ec604e0eb2be8a5b099da522
run_uuid: 1097f830ec604e0eb2be8a5b099da522
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439201008
status: 3
tags: []
user_id: abdoss
