artifact_uri: /mlflow_server/0/c1f253b0cbe64ced8eb66c2daf7717cf/artifacts
end_time: 1673437490724
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: c1f253b0cbe64ced8eb66c2daf7717cf
run_uuid: c1f253b0cbe64ced8eb66c2daf7717cf
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437489793
status: 3
tags: []
user_id: abdessamadbaahmed
