artifact_uri: /mlflow_server/0/dd8c2735c7294d84a1fdd3a72b5488e2/artifacts
end_time: 1673439212010
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: dd8c2735c7294d84a1fdd3a72b5488e2
run_uuid: dd8c2735c7294d84a1fdd3a72b5488e2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439210059
status: 3
tags: []
user_id: abdoss
