artifact_uri: /mlflow_server/0/ed4ae23948d749c4a9ee9b1f5f268123/artifacts
end_time: 1673439187882
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ed4ae23948d749c4a9ee9b1f5f268123
run_uuid: ed4ae23948d749c4a9ee9b1f5f268123
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439186901
status: 3
tags: []
user_id: abdoss
