artifact_uri: /mlflow_server/0/affda6695dab4381b4975b8ceaf9e415/artifacts
end_time: 1673437488134
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: affda6695dab4381b4975b8ceaf9e415
run_uuid: affda6695dab4381b4975b8ceaf9e415
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437487293
status: 3
tags: []
user_id: abdessamadbaahmed
