version: '3'
services:
  streamlit_app:
    build: streamlit_app/
    volumes:
      - ./streamlit_app/:/streamlit_app/
    ports:
      - 8501:8501
    #command: ["streamlit", "run", "src/Home.py", "--server.port=8501", "--server.address=0.0.0.0"]

  mlflow:
    build: mlflow_server/
    ports:
      - 5000:5000
    volumes:
      - ./mlflow_server:/mlflow/
    environment:
      - MLFLOW_TRACKING_URI=http://localhost:5000
    #command: ["mlflow", "server", "--host", "0.0.0.0"]

volumes:
  mlflow_server:

