version: '3'
services:

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: abdessamadbaahmed  
      MINIO_SECRET_KEY: baahmedabdessamad
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - mynetwork
    command: server --console-address ":9001" /data
    restart: always


  streamlit_app:
    build: streamlit_app/
    volumes:
      - ./streamlit_app/:/streamlit_app/
    ports:
      - 8501:8501
    networks:
      - mynetwork
    #command: ["streamlit", "run", "src/Home.py", "--server.port=8501", "--server.address=0.0.0.0"]

  mlflow_server:
    build: mlflow_server/
    ports:
      - 5000:5000
    volumes:
      - ./mlflow_server:/mlflow_server/
    networks:
      - mynetwork
    #environment:
    #  - MLFLOW_TRACKING_URI=http://localhost:5000
    #command: ["mlflow", "server", "--host", "0.0.0.0"]

  model_deployment_server:
    build: model_deployment_server/
    ports:
      - 4100:4100
    volumes:
      - ./model_deployment_server:/model_deployment_server/

    networks:
      - mynetwork

volumes:
  # not important due to the fact that the volume is only modified by the mlflow server (one service)
  mlflow_server:
  minio-data:
networks:
  mynetwork:
