artifact_uri: /mlflow_server/0/105b566619cc46d5a5e5eef439e303da/artifacts
end_time: 1673437460529
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 105b566619cc46d5a5e5eef439e303da
run_uuid: 105b566619cc46d5a5e5eef439e303da
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437459020
status: 3
tags: []
user_id: abdessamadbaahmed
