artifact_uri: /mlflow_server/0/46d54acdb7b24be0b0531dc1d03b2f5b/artifacts
end_time: 1673437495929
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 46d54acdb7b24be0b0531dc1d03b2f5b
run_uuid: 46d54acdb7b24be0b0531dc1d03b2f5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437495027
status: 3
tags: []
user_id: abdessamadbaahmed
