artifact_uri: /mlflow_server/0/b3cd9551def945d2896e5d610b7db8af/artifacts
end_time: 1673437489719
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b3cd9551def945d2896e5d610b7db8af
run_uuid: b3cd9551def945d2896e5d610b7db8af
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437488991
status: 3
tags: []
user_id: abdessamadbaahmed
