artifact_uri: /mlflow_server/0/13f8a25eab1a49ef82afcdb4e01293d8/artifacts
end_time: 1673437452261
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 13f8a25eab1a49ef82afcdb4e01293d8
run_uuid: 13f8a25eab1a49ef82afcdb4e01293d8
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437451430
status: 3
tags: []
user_id: abdessamadbaahmed
