artifact_uri: /mlflow_server/0/ce96b3a34ca745209fcb93cb45da931f/artifacts
end_time: 1673439183904
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ce96b3a34ca745209fcb93cb45da931f
run_uuid: ce96b3a34ca745209fcb93cb45da931f
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439183343
status: 3
tags: []
user_id: abdoss
