artifact_uri: /mlflow_server/0/b9e77a7ee5e94e55917880aadc4eb0c8/artifacts
end_time: 1673437464877
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b9e77a7ee5e94e55917880aadc4eb0c8
run_uuid: b9e77a7ee5e94e55917880aadc4eb0c8
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437463678
status: 3
tags: []
user_id: abdessamadbaahmed
