artifact_uri: /mlflow_server/0/a89df541acf94dcdb9784c0e568c3023/artifacts
end_time: 1673439491422
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: a89df541acf94dcdb9784c0e568c3023
run_uuid: a89df541acf94dcdb9784c0e568c3023
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439490794
status: 3
tags: []
user_id: abdoss
