artifact_uri: /mlflow_server/0/1c234c63450f42d09dfde6fb14d4bda9/artifacts
end_time: 1673437496920
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 1c234c63450f42d09dfde6fb14d4bda9
run_uuid: 1c234c63450f42d09dfde6fb14d4bda9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437495999
status: 3
tags: []
user_id: abdessamadbaahmed
