artifact_uri: /mlflow_server/0/d39ab2f6842340d5abb663d8804c54a9/artifacts
end_time: 1673437446412
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: d39ab2f6842340d5abb663d8804c54a9
run_uuid: d39ab2f6842340d5abb663d8804c54a9
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437445618
status: 3
tags: []
user_id: abdessamadbaahmed
