artifact_uri: /mlflow_server/0/eebefe7eab694063aeccd6f34074d843/artifacts
end_time: 1673437463611
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: eebefe7eab694063aeccd6f34074d843
run_uuid: eebefe7eab694063aeccd6f34074d843
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437460602
status: 3
tags: []
user_id: abdessamadbaahmed
