artifact_uri: /mlflow_server/0/9e1e7442c88a4dcc85a75a1b0da51c43/artifacts
end_time: 1673439185643
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9e1e7442c88a4dcc85a75a1b0da51c43
run_uuid: 9e1e7442c88a4dcc85a75a1b0da51c43
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439184969
status: 3
tags: []
user_id: abdoss
