artifact_uri: /mlflow_server/0/eb122b0591b44b48a2ba5f4a92c2f5ec/artifacts
end_time: 1673439210037
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: eb122b0591b44b48a2ba5f4a92c2f5ec
run_uuid: eb122b0591b44b48a2ba5f4a92c2f5ec
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439209345
status: 3
tags: []
user_id: abdoss
