artifact_uri: /mlflow_server/0/633d2c77433a4a3fa4c6d095078dece2/artifacts
end_time: 1673439215765
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 633d2c77433a4a3fa4c6d095078dece2
run_uuid: 633d2c77433a4a3fa4c6d095078dece2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439214475
status: 3
tags: []
user_id: abdoss
