artifact_uri: /mlflow_server/0/fb50ad545e7340ac910b8e573992b95b/artifacts
end_time: 1673437491536
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fb50ad545e7340ac910b8e573992b95b
run_uuid: fb50ad545e7340ac910b8e573992b95b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437490795
status: 3
tags: []
user_id: abdessamadbaahmed
