artifact_uri: /mlflow_server/0/f6ff7a94dda64c7a9d83c846705f8128/artifacts
end_time: 1673439189636
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f6ff7a94dda64c7a9d83c846705f8128
run_uuid: f6ff7a94dda64c7a9d83c846705f8128
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439188737
status: 3
tags: []
user_id: abdoss
