artifact_uri: /mlflow_server/0/56465aabb6d841d5a6b0d01539a0ed34/artifacts
end_time: 1673439225694
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 56465aabb6d841d5a6b0d01539a0ed34
run_uuid: 56465aabb6d841d5a6b0d01539a0ed34
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439221492
status: 3
tags: []
user_id: abdoss
