artifact_uri: /mlflow_server/0/05ade85a387f4eea9700372d63c4c5a0/artifacts
end_time: 1673439216193
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 05ade85a387f4eea9700372d63c4c5a0
run_uuid: 05ade85a387f4eea9700372d63c4c5a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439215788
status: 3
tags: []
user_id: abdoss
