artifact_uri: /mlflow_server/0/aad52578461b44cfb2e50446af975cda/artifacts
end_time: 1673437472801
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: aad52578461b44cfb2e50446af975cda
run_uuid: aad52578461b44cfb2e50446af975cda
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437471907
status: 3
tags: []
user_id: abdessamadbaahmed
