artifact_uri: /mlflow_server/0/67936f10d4bd4b7bb77e587b4905eac3/artifacts
end_time: 1673439214451
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 67936f10d4bd4b7bb77e587b4905eac3
run_uuid: 67936f10d4bd4b7bb77e587b4905eac3
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439212037
status: 3
tags: []
user_id: abdoss
