artifact_uri: /mlflow_server/0/0f95ba4504854c72af1f3ad78cee14a0/artifacts
end_time: 1673439351008
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 0f95ba4504854c72af1f3ad78cee14a0
run_uuid: 0f95ba4504854c72af1f3ad78cee14a0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439350131
status: 3
tags: []
user_id: abdoss
