artifact_uri: /mlflow_server/0/2a1d46a4810d4e34b221111dfab0b4f2/artifacts
end_time: 1673437481532
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2a1d46a4810d4e34b221111dfab0b4f2
run_uuid: 2a1d46a4810d4e34b221111dfab0b4f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437480635
status: 3
tags: []
user_id: abdessamadbaahmed
