artifact_uri: /mlflow_server/0/774d85e617eb4e91bfae01f7cfbcbb94/artifacts
end_time: 1673437458878
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 774d85e617eb4e91bfae01f7cfbcbb94
run_uuid: 774d85e617eb4e91bfae01f7cfbcbb94
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437457204
status: 3
tags: []
user_id: abdessamadbaahmed
