artifact_uri: /mlflow_server/0/848cf10de53f4d2eabac37ed0f0716ab/artifacts
end_time: 1673439205122
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 848cf10de53f4d2eabac37ed0f0716ab
run_uuid: 848cf10de53f4d2eabac37ed0f0716ab
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439203787
status: 3
tags: []
user_id: abdoss
