channels:
- conda-forge
dependencies:
- python=3.6.15
- pip
- pip:
  - mlflow
  - mypy-extensions==0.4.3
  - pandas==1.1.5
  - psutil==5.8.0
  - scikit-learn==0.24.2
  - typing-extensions==3.7.4.3
  - typing==3.7.4.3
  - xgboost==1.5.2
name: mlflow-env
