artifact_uri: /mlflow_server/0/8daa169a2a204a3ba3103e165b1c963b/artifacts
end_time: 1673437453886
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 8daa169a2a204a3ba3103e165b1c963b
run_uuid: 8daa169a2a204a3ba3103e165b1c963b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437452595
status: 3
tags: []
user_id: abdessamadbaahmed
