artifact_uri: /mlflow_server/0/f3a5f98149be4a108428a6d9a390e98d/artifacts
end_time: 1673437499103
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: f3a5f98149be4a108428a6d9a390e98d
run_uuid: f3a5f98149be4a108428a6d9a390e98d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437498254
status: 3
tags: []
user_id: abdessamadbaahmed
