artifact_uri: /mlflow_server/0/04ace2b8e9f149039cc4b2267ce1d4ae/artifacts
end_time: 1673439193583
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 04ace2b8e9f149039cc4b2267ce1d4ae
run_uuid: 04ace2b8e9f149039cc4b2267ce1d4ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439191530
status: 3
tags: []
user_id: abdoss
