artifact_uri: /mlflow_server/0/5fa636d0b6c040b887177dab5db54c73/artifacts
end_time: 1673437451352
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5fa636d0b6c040b887177dab5db54c73
run_uuid: 5fa636d0b6c040b887177dab5db54c73
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437450475
status: 3
tags: []
user_id: abdessamadbaahmed
