artifact_uri: /mlflow_server/0/5cd24f4a5b7548f89703cc757c52f7c0/artifacts
end_time: 1673437474121
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 5cd24f4a5b7548f89703cc757c52f7c0
run_uuid: 5cd24f4a5b7548f89703cc757c52f7c0
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437472888
status: 3
tags: []
user_id: abdessamadbaahmed
