artifact_uri: /mlflow_server/0/02b5958e79a44c418fea0bdc0e37fe5f/artifacts
end_time: 1673437477263
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 02b5958e79a44c418fea0bdc0e37fe5f
run_uuid: 02b5958e79a44c418fea0bdc0e37fe5f
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437476250
status: 3
tags: []
user_id: abdessamadbaahmed
