artifact_uri: /mlflow_server/0/9190e470bad64e4994135be5cc9a76bd/artifacts
end_time: 1673439186882
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9190e470bad64e4994135be5cc9a76bd
run_uuid: 9190e470bad64e4994135be5cc9a76bd
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439186378
status: 3
tags: []
user_id: abdoss
