artifact_uri: /mlflow_server/0/04dce17a954c4a4895df8e2bf131a216/artifacts
end_time: 1673437479552
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 04dce17a954c4a4895df8e2bf131a216
run_uuid: 04dce17a954c4a4895df8e2bf131a216
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437478613
status: 3
tags: []
user_id: abdessamadbaahmed
