artifact_uri: /mlflow_server/0/fd5ce11b8d1e4b80ac67380e3b78684d/artifacts
end_time: 1673437482490
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fd5ce11b8d1e4b80ac67380e3b78684d
run_uuid: fd5ce11b8d1e4b80ac67380e3b78684d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437481598
status: 3
tags: []
user_id: abdessamadbaahmed
