artifact_uri: /mlflow_server/0/795c8eb0dbb5471e99f82ad0eebee9ae/artifacts
end_time: 1673439182301
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 795c8eb0dbb5471e99f82ad0eebee9ae
run_uuid: 795c8eb0dbb5471e99f82ad0eebee9ae
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439181791
status: 3
tags: []
user_id: abdoss
