artifact_uri: /mlflow_server/0/b3709ec2bbbf443bb2661a22276eef51/artifacts
end_time: 1673437476173
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b3709ec2bbbf443bb2661a22276eef51
run_uuid: b3709ec2bbbf443bb2661a22276eef51
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437475263
status: 3
tags: []
user_id: abdessamadbaahmed
