artifact_uri: /mlflow_server/0/3b5f36b7b16248ddae6f3bbb4210429a/artifacts
end_time: 1673437471842
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3b5f36b7b16248ddae6f3bbb4210429a
run_uuid: 3b5f36b7b16248ddae6f3bbb4210429a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437470867
status: 3
tags: []
user_id: abdessamadbaahmed
