artifact_uri: /mlflow_server/0/78e1b7e3db08436589eb1b4c3cdb9cd8/artifacts
end_time: 1673437475187
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 78e1b7e3db08436589eb1b4c3cdb9cd8
run_uuid: 78e1b7e3db08436589eb1b4c3cdb9cd8
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437474205
status: 3
tags: []
user_id: abdessamadbaahmed
