artifact_uri: /mlflow_server/0/dedd77e922e048aa87be20e229c5100c/artifacts
end_time: 1673439190373
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: dedd77e922e048aa87be20e229c5100c
run_uuid: dedd77e922e048aa87be20e229c5100c
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439189651
status: 3
tags: []
user_id: abdoss
