artifact_uri: /mlflow_server/0/9cdae5de307e4608b30377303a9e71ba/artifacts
end_time: 1673439240911
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9cdae5de307e4608b30377303a9e71ba
run_uuid: 9cdae5de307e4608b30377303a9e71ba
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439236294
status: 3
tags: []
user_id: abdoss
