artifact_uri: /mlflow_server/0/b38cfb9dda8c4924af9539b903540e52/artifacts
end_time: 1673437469416
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: b38cfb9dda8c4924af9539b903540e52
run_uuid: b38cfb9dda8c4924af9539b903540e52
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437468341
status: 3
tags: []
user_id: abdessamadbaahmed
