artifact_uri: /mlflow_server/0/9708facbffa349a68ac271349b680422/artifacts
end_time: 1673437488921
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9708facbffa349a68ac271349b680422
run_uuid: 9708facbffa349a68ac271349b680422
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437488208
status: 3
tags: []
user_id: abdessamadbaahmed
