artifact_uri: /mlflow_server/0/344c325bcaa145d0acadc7d89210af7d/artifacts
end_time: 1673439205845
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 344c325bcaa145d0acadc7d89210af7d
run_uuid: 344c325bcaa145d0acadc7d89210af7d
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439205152
status: 3
tags: []
user_id: abdoss
