artifact_uri: /mlflow_server/0/2edec9023bc94bd7a00640c4ab68150b/artifacts
end_time: 1673437487215
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 2edec9023bc94bd7a00640c4ab68150b
run_uuid: 2edec9023bc94bd7a00640c4ab68150b
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437486426
status: 3
tags: []
user_id: abdessamadbaahmed
