artifact_uri: /mlflow_server/0/fcaca582add64d3ca55a89633e864c3a/artifacts
end_time: 1673437483277
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: fcaca582add64d3ca55a89633e864c3a
run_uuid: fcaca582add64d3ca55a89633e864c3a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437482560
status: 3
tags: []
user_id: abdessamadbaahmed
