artifact_uri: /mlflow_server/0/076b45406d9c446c9c425ea90eb8db78/artifacts
end_time: 1673437467267
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 076b45406d9c446c9c425ea90eb8db78
run_uuid: 076b45406d9c446c9c425ea90eb8db78
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437466130
status: 3
tags: []
user_id: abdessamadbaahmed
