artifact_uri: /mlflow_server/0/04cc3164f94848a3a1185afc68cbc965/artifacts
end_time: 1673437485388
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 04cc3164f94848a3a1185afc68cbc965
run_uuid: 04cc3164f94848a3a1185afc68cbc965
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437484306
status: 3
tags: []
user_id: abdessamadbaahmed
