artifact_uri: /mlflow_server/0/9dea4831bc264ff5addbbc8e46ff75e3/artifacts
end_time: 1673439186362
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9dea4831bc264ff5addbbc8e46ff75e3
run_uuid: 9dea4831bc264ff5addbbc8e46ff75e3
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439185659
status: 3
tags: []
user_id: abdoss
