artifact_uri: /mlflow_server/0/3e4d112c8ee34be4bac1a87e4c011d5a/artifacts
end_time: 1673437498155
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 3e4d112c8ee34be4bac1a87e4c011d5a
run_uuid: 3e4d112c8ee34be4bac1a87e4c011d5a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673437496985
status: 3
tags: []
user_id: abdessamadbaahmed
