channels:
- conda-forge
dependencies:
- python=3.9.15
- pip<=21.2.4
- pip:
  - mlflow<3,>=2.1
  - pandas==1.4.2
  - psutil==5.9.0
  - scikit-learn==1.1.0
  - typing-extensions==4.2.0
  - xgboost==1.7.2
name: mlflow-env
