artifact_uri: /mlflow_server/0/9bcbb1d1b3e34804a8a901ec0dce150a/artifacts
end_time: 1673439188717
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 9bcbb1d1b3e34804a8a901ec0dce150a
run_uuid: 9bcbb1d1b3e34804a8a901ec0dce150a
source_name: ''
source_type: 4
source_version: ''
start_time: 1673439187899
status: 3
tags: []
user_id: abdoss
